### ISSUE TITLE
It's possible to run libvisio2svg on macOS

### ISSUE THREAD

**Issue by eduardomozart** [lateralblast/viscid#2]
You can run libvisio2svg without Docker.
Please read https://translate.google.com/translate?sl=pt&tl=en&hl=pt-BR&u=https://eduardomozartdeoliveira.wordpress.com/2023/01/30/instalacao-do-libvisio2svg-no-macos/ for further instructions.

**Comment by richardatlateralblast** [comment]
No you can't reliably, especially on ARM. I used to compile it without issue 5 years ago, but it regularly fails these days, thus I use docker.

e.g.

/opt/homebrew/include/libwmf/ipa.h:72:15: warning: 'wmf_ipa_bmp_copy' has C-linkage specified, but returns incomplete type 'wmfBMP' (aka '_wmfBMP') which could be incompatible with C [-Wreturn-type-c-linkage]
   72 | extern wmfBMP wmf_ipa_bmp_copy (wmfAPI*,wmfBMP*,unsigned int,unsigned int);

**Comment by eduardomozart** [comment]
I was able to compile it and I use Mac on ARM using brew libraries. The message you posted is only a warning that do not affect libvisio compilation on macOS.
